commandlinefu_id: 14357
translator:
  weibo: ''
hide: true
command: |-
  ifconfig wlan0 | grep "inet addr:" | awk '{print $2}' | sed -e 's/.*:/\n\n\n/g' | sed 's/\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}/\t\t\t<--------= & =-------->\n\n\n\n\n/g'
summary: |-
  extract ip address from ifconfig using
